[general]

[rewrite]
enabled = false
shard_key = "ignore"
split_inserts = "error"

[[databases]]
name = "source"
host = "127.0.0.1"
database_name = "pgdog1"

[[databases]]
name = "destination"
host = "127.0.0.1"
database_name = "pgdog2"
