name: Install CI deps
runs:
  using: composite
  steps:
    - uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/cargo-nextest
          ~/.cargo/bin/cargo-llvm-cov
          ~/.local/cmake
        key: ci-tools-${{ runner.os }}-${{ hashFiles('integration/ci/install-deps.sh') }}
    - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_wait_seconds: 5
        command: bash integration/ci/install-deps.sh
