services:
  shard_0:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 6000:5432
    volumes:
      - shard_0:/var/lib/postgresql/data
  shard_1:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 6001:5432
    volumes:
      - shard_1:/var/lib/postgresql/data
  shard_2:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 6002:5432
    volumes:
      - shard_2:/var/lib/postgresql/data

volumes:
  shard_0:
  shard_1:
  shard_2:
