[package]
name = "pgdog-plugin-build"
version = "0.1.1"
edition = "2024"
authors = ["Lev Kokotov <lev@pgdog.dev> "]
license = "MIT"
description = "Build-time helpers for PgDog plugins"

[dependencies]
toml = "0.9"
