services:
  gel:
    image: geldata/gel:latest
    environment:
      GEL_SERVER_PASSWORD: gel
      GEL_SERVER_TLS_CERT_MODE: generate_self_signed
      GEL_SERVER_BACKEND_DSN: postgres://postgres:postgres@pgdog:6432/postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
  pgdog:
    build:
      dockerfile: Dockerfile
      context: ../../
    environment:
      RUST_LOG: debug
    command:
      - "/usr/local/bin/pgdog"
      - "--config"
      - "/etc/pgdog/pgdog.toml"
      - "--users"
      - "/etc/pgdog/users.toml"
      - "run"
      - "--min-pool-size=0"
    volumes:
      - ./:/etc/pgdog
