//! Schema operations.
pub mod columns;
pub mod relation;
pub mod sync;

use pg_query::{
    protobuf::{
        ColumnDef, ConstrType, Constraint, CreateStmt, OnCommitAction, RangeVar,
        String as PgString, TypeName,
    },
    Node, NodeEnum,
};
pub use pgdog_stats::{
    Relation as StatsRelation, Relations as StatsRelations, Schema as StatsSchema, SchemaInner,
};
use serde::{Deserialize, Serialize};
use std::ops::DerefMut;
use std::{collections::HashMap, ops::Deref};
use tracing::info;

pub use relation::Relation;

use super::{pool::Request, Cluster, Error, Server};
use crate::frontend::router::parser::Table;
use crate::net::parameter::ParameterValue;
use sync::ShardConfig;

static SETUP: &str = include_str!("setup.sql");

/// Load schema from database.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Hash)]
pub struct Schema {
    inner: StatsSchema,
}

impl Deref for Schema {
    type Target = StatsSchema;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl DerefMut for Schema {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.inner
    }
}

impl Schema {
    /// Load schema from a server connection.
    pub async fn load(server: &mut Server) -> Result<Self, Error> {
        let mut relations: StatsRelations = HashMap::new();
        for relation in Relation::load(server).await? {
            relations
                .entry(relation.schema().to_owned())
                .or_default()
                .insert(relation.name.clone(), relation.into());
        }

        let search_path = server
            .fetch_all::<String>("SHOW search_path")
            .await?
            .pop()
            .unwrap_or(String::from("$user, public"))
            .split(",")
            .map(|p| p.trim().replace("\"", ""))
            .collect();

        let inner = SchemaInner {
            search_path,
            relations,
        };

        Ok(Self {
            inner: StatsSchema::new(inner),
        })
    }

    /// The schema has been loaded from the database.
    pub(crate) fn is_loaded(&self) -> bool {
        !self.inner.relations.is_empty()
    }

    #[cfg(test)]
    pub(crate) fn from_parts(
        search_path: Vec<String>,
        relations: HashMap<(String, String), Relation>,
    ) -> Self {
        let mut nested: StatsRelations = HashMap::new();
        for ((schema, name), relation) in relations {
            nested
                .entry(schema)
                .or_default()
                .insert(name, relation.into());
        }
        Self {
            inner: StatsSchema::new(SchemaInner {
                search_path,
                relations: nested,
            }),
        }
    }

    /// Install PgDog functions and schema.
    pub async fn setup(server: &mut Server) -> Result<(), Error> {
        server.execute_checked(SETUP).await?;
        Ok(())
    }

    async fn install_server(server: &mut Server) -> Result<(), Error> {
        Self::setup(server).await?;
        let schema = Self::load(server).await?;

        let tables = schema
            .tables()
            .iter()
            .cloned()
            // Skip partition children: PostgreSQL forbids ALTER TABLE <child>
            // DROP IDENTITY (error 42P16). The partitioned parent's
            // install_shadow_table call handles the entire hierarchy because
            // DROP IDENTITY and SET DEFAULT on a partitioned parent propagate
            // to all partition children automatically.
            .filter(|table| {
                !matches!(table.schema.as_str(), "pgdog" | "pgdog_shadow")
                    && table.parent_table_name.is_none()
            })
            .collect::<Vec<_>>();

        info!(
            "[schema] checking {} tables for sharded sequences [{}]",
            tables.len(),
            server.addr(),
        );

        let supported_defaults = [
            "nextval",
            "generated always as identity",
            "generated by default as identity",
        ];

        for table in tables {
            for column in table.columns().iter().filter(|column| {
                column.1.is_primary_key // Only primary keys.
                    && matches!(column.1.data_type.as_str(), "bigint" | "int8") // Only BIGINT.
                    && supported_defaults.iter().any(|p| column.1.column_default.contains(p))
                // Only the ones that rely on a sequence.
            }) {
                info!(
                    "[schema] creating sharded sequence for \"{}\".\"{}\".\"{}\"",
                    column.1.table_schema, column.1.table_name, column.1.column_name,
                );

                let query = format!(
                    "SELECT pgdog.install_shadow_table('{}', '{}', '{}')",
                    column.1.table_schema, column.1.table_name, column.1.column_name,
                );

                server.execute_checked(&query).await?;
            }
        }

        info!("[schema] sharded sequence check done [{}]", server.addr());

        Ok(())
    }

    /// Install PgDog-specific functions and triggers.
    pub async fn install(cluster: &Cluster) -> Result<(), Error> {
        let shards = cluster.shards();
        let sharded_tables = cluster.sharded_tables();

        if sharded_tables.is_empty() {
            return Ok(());
        }

        // Sync configuration.
        ShardConfig::sync_all(cluster).await?;

        for shard in shards {
            let mut server = shard.primary(&Request::default()).await?;
            Self::install_server(&mut server).await?;
        }

        Ok(())
    }

    /// Get table by name.
    ///
    /// If the table has an explicit schema, looks up in that schema directly.
    /// Otherwise, iterates through the search_path to find the first match.
    pub fn table(
        &self,
        table: Table<'_>,
        user: &str,
        search_path: Option<&ParameterValue>,
    ) -> Option<&StatsRelation> {
        if let Some(schema) = table.schema {
            return self.inner.get(schema, table.name);
        }

        for schema in self.resolve_search_path(user, search_path) {
            if let Some(relation) = self.inner.get(schema, table.name) {
                return Some(relation);
            }
        }

        None
    }

    fn resolve_search_path<'a>(
        &'a self,
        user: &'a str,
        search_path: Option<&'a ParameterValue>,
    ) -> Vec<&'a str> {
        let path: &[String] = match search_path {
            Some(ParameterValue::Tuple(overriden)) => overriden.as_slice(),
            _ => &self.inner.search_path,
        };

        path.iter()
            .map(|p| if p == "$user" { user } else { p.as_str() })
            .collect()
    }

    /// Get all tables.
    pub fn tables(&self) -> Vec<&StatsRelation> {
        self.inner
            .relations
            .values()
            .flat_map(|tables| tables.values())
            .filter(|relation| relation.is_table())
            .collect()
    }

    /// Get all sequences.
    pub fn sequences(&self) -> Vec<&StatsRelation> {
        self.inner
            .relations
            .values()
            .flat_map(|tables| tables.values())
            .filter(|relation| relation.is_sequence())
            .collect()
    }

    /// Get search path components.
    pub fn search_path(&self) -> &[String] {
        &self.inner.search_path
    }

    /// Generate a `CREATE TABLE` statement for a relation in the schema.
    pub fn to_sql(&self, schema: &str, table: &str) -> Option<String> {
        let relation = self.inner.get(schema, table)?;

        let mut table_elts = Vec::with_capacity(relation.columns.len());
        let mut pk_columns = Vec::new();

        for column in relation.columns.values() {
            let mut constraints = Vec::new();

            if !column.is_nullable {
                constraints.push(Node {
                    node: Some(NodeEnum::Constraint(Box::new(Constraint {
                        contype: ConstrType::ConstrNotnull.into(),
                        ..Default::default()
                    }))),
                });
            }

            if !column.column_default.is_empty() {
                if let Some(expr) = Self::parse_default_expr(&column.column_default) {
                    constraints.push(Node {
                        node: Some(NodeEnum::Constraint(Box::new(Constraint {
                            contype: ConstrType::ConstrDefault.into(),
                            raw_expr: Some(Box::new(expr)),
                            ..Default::default()
                        }))),
                    });
                }
            }

            if column.is_primary_key {
                pk_columns.push(Node {
                    node: Some(NodeEnum::String(PgString {
                        sval: column.column_name.clone(),
                    })),
                });
            }

            table_elts.push(Node {
                node: Some(NodeEnum::ColumnDef(Box::new(ColumnDef {
                    colname: column.column_name.clone(),
                    type_name: Some(Self::pg_type_name(&column.data_type)),
                    is_local: true,
                    constraints,
                    ..Default::default()
                }))),
            });
        }

        if !pk_columns.is_empty() {
            table_elts.push(Node {
                node: Some(NodeEnum::Constraint(Box::new(Constraint {
                    contype: ConstrType::ConstrPrimary.into(),
                    keys: pk_columns,
                    ..Default::default()
                }))),
            });
        }

        let create_stmt = CreateStmt {
            relation: Some(RangeVar {
                schemaname: schema.to_owned(),
                relname: table.to_owned(),
                inh: true,
                relpersistence: "p".to_owned(),
                ..Default::default()
            }),
            table_elts,
            oncommit: OnCommitAction::OncommitNoop.into(),
            ..Default::default()
        };

        NodeEnum::CreateStmt(create_stmt).deparse().ok()
    }

    /// Parse a column default expression into an AST node.
    fn parse_default_expr(default: &str) -> Option<Node> {
        let parsed = pg_query::parse(&format!("SELECT {default}")).ok()?;
        let stmt = parsed.protobuf.stmts.first()?;
        let node = stmt.stmt.as_ref()?;
        let NodeEnum::SelectStmt(ref select) = node.node.as_ref()? else {
            return None;
        };
        let target = select.target_list.first()?;
        let NodeEnum::ResTarget(ref res) = target.node.as_ref()? else {
            return None;
        };
        res.val.as_ref().map(|v| (**v).clone())
    }

    /// Map an information_schema data type name to a pg_catalog [`TypeName`].
    fn pg_type_name(data_type: &str) -> TypeName {
        // Types that deparse correctly with pg_catalog qualification.
        let pg_catalog_name = match data_type {
            "bigint" => Some("int8"),
            "integer" => Some("int4"),
            "smallint" => Some("int2"),
            "boolean" => Some("bool"),
            "character varying" => Some("varchar"),
            "double precision" => Some("float8"),
            "real" => Some("float4"),
            "timestamp without time zone" => Some("timestamp"),
            "timestamp with time zone" => Some("timestamptz"),
            "character" => Some("bpchar"),
            _ => None,
        };

        let names = if let Some(pg_name) = pg_catalog_name {
            vec![
                Node {
                    node: Some(NodeEnum::String(PgString {
                        sval: "pg_catalog".to_owned(),
                    })),
                },
                Node {
                    node: Some(NodeEnum::String(PgString {
                        sval: pg_name.to_owned(),
                    })),
                },
            ]
        } else {
            vec![Node {
                node: Some(NodeEnum::String(PgString {
                    sval: data_type.to_owned(),
                })),
            }]
        };

        TypeName {
            names,
            typemod: -1,
            ..Default::default()
        }
    }
}

#[cfg(test)]
mod test {
    use std::collections::HashMap;

    use indexmap::IndexMap;

    use crate::backend::pool::Request;
    use crate::backend::schema::relation::Relation;
    use crate::backend::server::test::test_server;
    use crate::frontend::router::parser::Table;
    use crate::net::parameter::ParameterValue;

    use super::super::pool::test::pool;
    use super::Schema;

    #[tokio::test]
    async fn test_schema() {
        let pool = pool();
        let mut conn = pool.get(&Request::default()).await.unwrap();
        conn.execute("DROP SCHEMA IF EXISTS pgdog CASCADE")
            .await
            .unwrap();
        let _schema = Schema::load(&mut conn).await.unwrap();
        Schema::setup(&mut conn).await.unwrap();
        let schema = Schema::load(&mut conn).await.unwrap();
        let seq = schema
            .sequences()
            .into_iter()
            .find(|seq| seq.schema() == "pgdog")
            .cloned()
            .unwrap();
        assert!(
            matches!(
                seq.name.as_str(),
                "unique_id_seq" | "validator_bigint_id_seq"
            ),
            "{}",
            seq.name
        );

        let server_ok = conn.fetch_all::<i32>("SELECT 1 AS one").await.unwrap();
        assert_eq!(server_ok.first().unwrap().clone(), 1);

        let debug = conn
            .fetch_all::<String>("SELECT pgdog.debug()")
            .await
            .unwrap();
        assert!(debug.first().unwrap().contains("PgDog Debug"));
    }

    #[tokio::test]
    async fn test_install_next_id_seq() {
        use crate::backend::server::test::test_server;

        let mut conn = test_server().await;

        // Use a dedicated schema to avoid conflicts with test_schema
        // which drops the pgdog schema.
        conn.execute_checked("CREATE SCHEMA IF NOT EXISTS pgdog_test")
            .await
            .unwrap();

        // Install pgdog schema (CREATE OR REPLACE is idempotent).
        Schema::setup(&mut conn).await.unwrap();

        // Ensure shard config exists.
        let count = conn
            .fetch_all::<i64>("SELECT COUNT(*) FROM pgdog.config")
            .await
            .unwrap();
        if count.first().copied() == Some(0) {
            conn.execute_checked("INSERT INTO pgdog.config (shard, shards) VALUES (0, 1)")
                .await
                .unwrap();
        }

        // Clean up from previous runs and create a test table with BIGSERIAL primary key.
        conn.execute_checked("DROP TABLE IF EXISTS pgdog_test.ids")
            .await
            .unwrap();
        conn.execute_checked("CREATE TABLE pgdog_test.ids (id BIGSERIAL PRIMARY KEY, value TEXT)")
            .await
            .unwrap();

        // Install the sharded sequence via install_next_id_seq.
        let result = conn
            .fetch_all::<String>("SELECT pgdog.install_next_id_seq('pgdog_test', 'ids', 'id')")
            .await
            .unwrap();
        assert!(
            result.first().unwrap().contains("installed"),
            "{}",
            result.first().unwrap()
        );

        // Insert rows and collect generated IDs.
        conn.execute_checked("INSERT INTO pgdog_test.ids (value) VALUES ('a')")
            .await
            .unwrap();
        conn.execute_checked("INSERT INTO pgdog_test.ids (value) VALUES ('b')")
            .await
            .unwrap();
        conn.execute_checked("INSERT INTO pgdog_test.ids (value) VALUES ('c')")
            .await
            .unwrap();

        let ids = conn
            .fetch_all::<i64>("SELECT id FROM pgdog_test.ids ORDER BY id")
            .await
            .unwrap();

        assert_eq!(ids.len(), 3);

        // All IDs should be unique.
        let mut unique = ids.clone();
        unique.sort();
        unique.dedup();
        assert_eq!(unique.len(), 3, "IDs are not unique: {:?}", ids);

        // Clean up.
        conn.execute_checked("DROP SCHEMA pgdog_test CASCADE")
            .await
            .unwrap();
    }

    #[test]
    fn test_resolve_search_path_default() {
        let schema = Schema::from_parts(vec!["$user".into(), "public".into()], HashMap::new());

        let resolved = schema.resolve_search_path("alice", None);
        assert_eq!(resolved, vec!["alice", "public"]);
    }

    #[test]
    fn test_resolve_search_path_override() {
        let schema = Schema::from_parts(vec!["$user".into(), "public".into()], HashMap::new());

        let override_path = ParameterValue::Tuple(vec!["custom".into(), "other".into()]);
        let resolved = schema.resolve_search_path("alice", Some(&override_path));
        assert_eq!(resolved, vec!["custom", "other"]);
    }

    #[test]
    fn test_resolve_search_path_override_with_user() {
        let schema = Schema::from_parts(vec!["public".into()], HashMap::new());

        let override_path = ParameterValue::Tuple(vec!["$user".into(), "app".into()]);
        let resolved = schema.resolve_search_path("bob", Some(&override_path));
        assert_eq!(resolved, vec!["bob", "app"]);
    }

    #[test]
    fn test_table_with_explicit_schema() {
        let relations: HashMap<(String, String), Relation> = HashMap::from([
            (
                ("myschema".into(), "users".into()),
                Relation::test_table("myschema", "users", IndexMap::new()),
            ),
            (
                ("public".into(), "users".into()),
                Relation::test_table("public", "users", IndexMap::new()),
            ),
        ]);
        let schema = Schema::from_parts(vec!["$user".into(), "public".into()], relations);

        let table = Table {
            name: "users",
            schema: Some("myschema"),
            alias: None,
        };

        let result = schema.table(table, "alice", None);
        assert!(result.is_some());
        assert_eq!(result.unwrap().schema(), "myschema");
    }

    #[test]
    fn test_table_search_path_lookup() {
        let relations: HashMap<(String, String), Relation> = HashMap::from([(
            ("public".into(), "orders".into()),
            Relation::test_table("public", "orders", IndexMap::new()),
        )]);
        let schema = Schema::from_parts(vec!["$user".into(), "public".into()], relations);

        let table = Table {
            name: "orders",
            schema: None,
            alias: None,
        };

        // User schema "alice" doesn't have "orders", but "public" does
        let result = schema.table(table, "alice", None);
        assert!(result.is_some());
        assert_eq!(result.unwrap().schema(), "public");
    }

    #[test]
    fn test_table_found_in_user_schema() {
        let relations: HashMap<(String, String), Relation> = HashMap::from([
            (
                ("alice".into(), "settings".into()),
                Relation::test_table("alice", "settings", IndexMap::new()),
            ),
            (
                ("public".into(), "settings".into()),
                Relation::test_table("public", "settings", IndexMap::new()),
            ),
        ]);
        let schema = Schema::from_parts(vec!["$user".into(), "public".into()], relations);

        let table = Table {
            name: "settings",
            schema: None,
            alias: None,
        };

        // Should find in "alice" schema first (due to $user)
        let result = schema.table(table, "alice", None);
        assert!(result.is_some());
        assert_eq!(result.unwrap().schema(), "alice");
    }

    #[test]
    fn test_table_not_found() {
        let relations: HashMap<(String, String), Relation> = HashMap::from([(
            ("public".into(), "users".into()),
            Relation::test_table("public", "users", IndexMap::new()),
        )]);
        let schema = Schema::from_parts(vec!["$user".into(), "public".into()], relations);

        let table = Table {
            name: "nonexistent",
            schema: None,
            alias: None,
        };

        let result = schema.table(table, "alice", None);
        assert!(result.is_none());
    }

    #[test]
    fn test_table_with_overridden_search_path() {
        let relations: HashMap<(String, String), Relation> = HashMap::from([
            (
                ("custom".into(), "data".into()),
                Relation::test_table("custom", "data", IndexMap::new()),
            ),
            (
                ("public".into(), "data".into()),
                Relation::test_table("public", "data", IndexMap::new()),
            ),
        ]);
        let schema = Schema::from_parts(vec!["$user".into(), "public".into()], relations);

        let table = Table {
            name: "data",
            schema: None,
            alias: None,
        };

        // Override search_path to look in "custom" first
        let override_path = ParameterValue::Tuple(vec!["custom".into(), "public".into()]);
        let result = schema.table(table, "alice", Some(&override_path));
        assert!(result.is_some());
        assert_eq!(result.unwrap().schema(), "custom");
    }

    #[test]
    fn test_to_sql() {
        use crate::backend::schema::columns::Column;

        fn col(
            name: &str,
            table: &str,
            data_type: &str,
            ordinal: i32,
            pk: bool,
            nullable: bool,
        ) -> Column {
            pgdog_stats::Column {
                table_catalog: String::new(),
                table_schema: "public".into(),
                table_name: table.into(),
                column_name: name.into(),
                column_default: String::new(),
                is_nullable: nullable,
                data_type: data_type.into(),
                ordinal_position: ordinal,
                is_primary_key: pk,
                foreign_keys: vec![],
            }
            .into()
        }

        let columns = IndexMap::from([
            (
                "id".to_owned(),
                col("id", "users", "bigint", 1, true, false),
            ),
            (
                "name".to_owned(),
                col("name", "users", "text", 2, false, false),
            ),
            (
                "email".to_owned(),
                col("email", "users", "character varying", 3, false, true),
            ),
        ]);

        let relations: HashMap<(String, String), Relation> = HashMap::from([(
            ("public".into(), "users".into()),
            Relation::test_table("public", "users", columns),
        )]);
        let schema = Schema::from_parts(vec!["public".into()], relations);

        let sql = schema.to_sql("public", "users").unwrap();
        assert!(sql.contains("CREATE TABLE"), "{sql}");
        assert!(sql.contains("public"), "{sql}");
        assert!(sql.contains("users"), "{sql}");
        assert!(sql.contains("id"), "{sql}");
        assert!(sql.contains("name"), "{sql}");
        assert!(sql.contains("email"), "{sql}");
        assert!(sql.contains("PRIMARY KEY"), "{sql}");
    }

    #[test]
    fn test_to_sql_not_found() {
        let schema = Schema::from_parts(vec!["public".into()], HashMap::new());
        assert!(schema.to_sql("public", "nonexistent").is_none());
    }

    #[tokio::test]
    async fn test_identity_column() {
        let mut server = test_server().await;
        // Drop and recreate the schema so the test is repeatable.
        server
            .execute_checked("DROP SCHEMA IF EXISTS pgdog_schema_test CASCADE")
            .await
            .unwrap();
        server
            .execute_checked("DROP SCHEMA IF EXISTS pgdog_shadow CASCADE")
            .await
            .unwrap();
        server
            .execute_checked(include_str!("test_schema.sql"))
            .await
            .unwrap();
        Schema::install_server(&mut server).await.unwrap();

        // Verify the partitioned parents had identity dropped and a sharded
        // sequence default installed. Children inherit the default from the
        // parent so they should NOT have been touched directly (which would
        // raise error 42P16).
        let parents = ["partitioned_identity", "partitioned_identity_compound"];
        for parent in parents {
            let identity: Vec<String> = server
                .fetch_all::<String>(&format!(
                    "SELECT is_identity FROM information_schema.columns \
                     WHERE table_schema = 'pgdog_schema_test' \
                     AND table_name = '{parent}' AND column_name = 'id'"
                ))
                .await
                .unwrap();
            assert_eq!(
                identity.first().map(String::as_str),
                Some("NO"),
                "{parent}.id should no longer be identity after install_server",
            );

            let default: Vec<String> = server
                .fetch_all::<String>(&format!(
                    "SELECT column_default FROM information_schema.columns \
                     WHERE table_schema = 'pgdog_schema_test' \
                     AND table_name = '{parent}' AND column_name = 'id'"
                ))
                .await
                .unwrap();
            assert!(
                default.first().is_some_and(|d| d.contains("next_id_seq")),
                "{parent}.id should have a next_id_seq default, got {:?}",
                default.first(),
            );
        }
    }
}
