-- Test schema covering all bigint primary key variations that match the install filter.
-- Each table uses a different mechanism for generating bigint primary keys.

CREATE SCHEMA IF NOT EXISTS pgdog_schema_test;

-- 1. BIGSERIAL PRIMARY KEY (column_default contains "nextval")
CREATE TABLE pgdog_schema_test.bigserial_pk (
    id BIGSERIAL PRIMARY KEY,
    value TEXT
);

-- 2. BIGSERIAL on a partitioned parent, with a child partition.
--    Tests that partition parents are processed before children.
CREATE TABLE pgdog_schema_test.partitioned_bigserial (
    id BIGSERIAL,
    created_at DATE NOT NULL,
    value TEXT,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE pgdog_schema_test.partitioned_bigserial_child
    PARTITION OF pgdog_schema_test.partitioned_bigserial
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

-- 3. BIGINT GENERATED ALWAYS AS IDENTITY
CREATE TABLE pgdog_schema_test.always_identity_pk (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    value TEXT
);

-- 4. BIGINT GENERATED BY DEFAULT AS IDENTITY
CREATE TABLE pgdog_schema_test.by_default_identity_pk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT
);

-- 5. Partitioned table (GENERATED ALWAYS AS IDENTITY) with a child partition.
CREATE TABLE pgdog_schema_test.partitioned_identity (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    created_at DATE NOT NULL,
    value TEXT,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE pgdog_schema_test.partitioned_identity_child
    PARTITION OF pgdog_schema_test.partitioned_identity
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

-- 6. Partitioned table with compound primary key (BIGSERIAL id + tenant_id).
CREATE TABLE pgdog_schema_test.partitioned_compound (
    id BIGSERIAL,
    tenant_id INT NOT NULL,
    value TEXT,
    PRIMARY KEY (id, tenant_id)
) PARTITION BY HASH (tenant_id);

CREATE TABLE pgdog_schema_test.partitioned_compound_0
    PARTITION OF pgdog_schema_test.partitioned_compound
    FOR VALUES WITH (MODULUS 2, REMAINDER 0);

CREATE TABLE pgdog_schema_test.partitioned_compound_1
    PARTITION OF pgdog_schema_test.partitioned_compound
    FOR VALUES WITH (MODULUS 2, REMAINDER 1);
