#
# minimal pgDog configuration for a single user, single
# primary database running on the same host.
#
[general]
host = "0.0.0.0"
port = 6432
shutdown_timeout = 5_000
openmetrics_port = 9090

#
# Admin database password.
#
[admin]
password = "pgdog"

#
# Simple database.
#
[[databases]]
name = "pgdog"
host = "127.0.0.1"
port = 5432

[tcp]
retries = 3
time = 1000
interval = 1000


#
# Sharded cluster with two primaries.
#
[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_0"
shard = 0

[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_1"
shard = 1

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5433
role = "primary"
database_name = "pgdog"

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5434
role = "replica"
database_name = "pgdog"

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5435
role = "replica"
database_name = "pgdog"

#
# Read/write access to theses tables will be automatically
# sharded.
#
[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded"
column = "id"
data_type = "bigint"
primary = true

[[sharded_tables]]
database = "pgdog_sharded"
name = "users"
data_type = "bigint"
column = "id"
primary = true

[[sharded_tables]]
database = "pgdog_sharded"
name = "embeddings"
data_type = "vector"
column = "embedding"
centroids_path = "examples/pgvector/centroids.json"

#
# ActiveRecord sends these queries
# at startup to figure out the schema.
#
# This will route them to only one shard instead of issuing
# cross-shard queries and getting incorrect results.
#
[[manual_queries]]
fingerprint = "e78fe2c08de5f079" #[16685804461073231993]

[[manual_queries]]
fingerprint = "43258d068030bb3e" #[4838428433739463486]

[[manual_queries]]
fingerprint = "08aab2cee482a97d" #[624508100011010429]

[[manual_queries]]
fingerprint = "23cd60d5972d1712" #[2579824632033777426]

[[manual_queries]]
fingerprint = "bb38525ebeb46656" #[13490623250668217942]
