#
# minimal pgDog configuration for a single user, single
# primary database running on the same host.
#
[general]
host = "0.0.0.0"
port = 6432
shutdown_timeout = 5_000
openmetrics_port = 9090
query_timeout = 1_000
checkout_timeout = 1_000
connect_timeout = 1_000
passthrough_auth = "enabled_plain"
idle_timeout = 30_000
prepared_statements = "extended"
# dry_run = true

#
# Admin database password.
#
[admin]
password = "pgdog"

#
# Simple database.
#
[[databases]]
name = "pgdog"
host = "127.0.0.1"
port = 5432
role = "primary"

# [[databases]]
# name = "pgdog"
# host = "127.0.0.1"
# port = 5432
# role = "replica"

[[databases]]
name = "mastodon_development"
host = "127.0.0.1"
role = "primary"

[[databases]]
name = "mastodon_development"
host = "127.0.0.1"
role = "replica"

[tcp]
retries = 3
time = 1000
interval = 1000
user_timeout = 1000


#
# Sharded cluster with two primaries.
#
[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_0"
shard = 0

[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_1"
shard = 1

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5435
role = "primary"
database_name = "pgdog"

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5436
role = "replica"
database_name = "pgdog"

#
# Read/write access to theses tables will be automatically
# sharded.
#
[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded"
column = "id"
data_type = "bigint"
primary = true

[[sharded_tables]]
database = "pgdog_sharded"
name = "users"
data_type = "bigint"
column = "id"
primary = true

[[omnisharded_tables]]
database = "pgdog_sharded"
tables = [
    "sharded_omni"
]

[[sharded_tables]]
database = "pgdog_sharded"
name = "embeddings"
data_type = "vector"
column = "embedding"
centroids_path = "examples/pgvector/centroids.json"

[[sharded_tables]]
database = "mastodon_development"
data_type = "bigint"
column = "account_id"

[[sharded_tables]]
database = "mastodon_development"
data_type = "bigint"
name = "accounts"
column = "id"

[[sharded_tables]]
database = "mastodon_development"
column = "remote_account_id"

[[sharded_tables]]
database = "mastodon_development"
column = "target_account_id"

[[sharded_tables]]
database = "mastodon_development"
column = "reference_account_id"

[[sharded_tables]]
database = "mastodon_development"
column = "from_account_id"

[[sharded_tables]]
database = "mastodon_development"
column = "action_taken_by_account_id"

[[omnisharded_tables]]
database = "mastodon_development"
tables = [
    "settings",
    "settings",
    "site_uploads",
    "ip_blocks",
    "terms_of_services",
    "account_statuses_cleanup_policies",
]


#
# ActiveRecord sends these queries
# at startup to figure out the schema.
#
# This will route them to only one shard instead of issuing
# cross-shard queries and getting incorrect results.
#
[[manual_queries]]
fingerprint = "e78fe2c08de5f079" #[16685804461073231993]

[[manual_queries]]
fingerprint = "43258d068030bb3e" #[4838428433739463486]

[[manual_queries]]
fingerprint = "08aab2cee482a97d" #[624508100011010429]

[[manual_queries]]
fingerprint = "23cd60d5972d1712" #[2579824632033777426]

[[manual_queries]]
fingerprint = "bb38525ebeb46656" #[13490623250668217942]

[[manual_query]]
fingerprint = "f4814b6fadabc4c1" #[17618446160277259457]
