# Basic users configuration.
#
# Two users:
#
# - pgdog: in transaction mode, default settings
# - pgdog_session: in session mode, other settings are default
#
[[users]]
name = "pgdog"
database = "pgdog"
password = "pgdog"
pooler_mode = "session"
