[general]
mirror_exposure = 1.0
openmetrics_port = 9090

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[[databases]]
name = "pgdog_mirror"
host = "127.0.0.1"
database_name = "pgdog1"

[[mirroring]]
source_db = "pgdog"
destination_db = "pgdog_mirror"

[admin]
password = "pgdog"
