[general]
openmetrics_port = 9090

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[[databases]]
name = "pgdog_mirror"
host = "127.0.0.1"
database_name = "pgdog1"

[[mirroring]]
source = "pgdog"
destination = "pgdog_mirror"
exposure = 1.0
queue_depth = 128

[admin]
password = "pgdog"
