services:
  primary:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/primary.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - 45000:5432
  replica_1:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/replica.sh:/docker-entrypoint-initdb.d/setup.sh
    user: postgres
    entrypoint:
      - bash
      - /docker-entrypoint-initdb.d/setup.sh
    ports:
      - 45001:5432
  replica_2:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/replica.sh:/docker-entrypoint-initdb.d/setup.sh
    user: postgres
    entrypoint:
      - bash
      - /docker-entrypoint-initdb.d/setup.sh
    ports:
      - 45002:5432
