[[databases]]
name = "pgdog"
host = "127.0.0.1"

[[databases]]
name = "source"
host = "127.0.0.1"
port = 5432
database_name = "pgdog"

[[databases]]
name = "destination"
host = "127.0.0.1"
port = 5433
database_name = "pgdog"
