[[users]]
database = "pgdog"
name = "pgdog"
password = "pgdog"
replication_mode = true

[[users]]
database = "source"
name = "pgdog"
password = "pgdog"

[[users]]
database = "destination"
name = "pgdog"
password = "pgdog"
