[general]
query_timeout = 60000
shutdown_timeout = 0
shutdown_termination_timeout = 1000

[rewrite]
enabled = false
shard_key = "ignore"
split_inserts = "error"

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[admin]
password = "pgdog"
