[general]
query_timeout = 60000
shutdown_timeout = 0
shutdown_termination_timeout = 1000
rewrite_shard_key_updates = "ignore"

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[admin]
password = "pgdog"
