[[databases]]
name = "database_name"
host = "server_address"
role = "primary"
#shard = 0

#[[databases]]
#name = "database_name"
#host = "server_address"
#role = "primary"
#shard = 1

[result_cache]
enabled = true
redis_url = "redis://redis:6379"
expire_seconds = 60
max_entry_bytes = 524288
key_prefix = "pgdog:result_cache"
encryption_key = "uma-chave-secreta-muito-longa-e-dificil-de-adivinhar-aqui-321"
