[general]
query_timeout = 5_000

[[databases]]
name = "pgdog"
host = "127.0.0.1"
port = 5435
role = "primary"

[[databases]]
name = "pgdog"
host = "127.0.0.1"
port = 5436
role = "replica"

[tcp]
keepalive = true
interval = 1_000
time =  1_000
retries = 3

[admin]
password = "pgdog"
