[general]
cross_shard_disabled = true

# Key! It's default but emphasized here due to the default integration config using aggressive.
read_write_strategy = "conservative"

[[databases]]
host = "127.0.0.1"
name = "pgdog"
shard = 0

[[databases]]
host = "127.0.0.1"
name = "pgdog"
shard = 1

[[sharded_schemas]]
database = "pgdog"
name = "customer_a"
shard = 0

[[sharded_schemas]]
database = "pgdog"
name = "customer_b"
shard = 1