# Test users for GSSAPI authentication testing

[[user]]
name = "test"
principal = "test@PGDOG.LOCAL"
strip_realm = true

[[user]]
name = "pgdog-test"
principal = "pgdog-test@PGDOG.LOCAL"
strip_realm = true

[[user]]
name = "server1"
principal = "server1@PGDOG.LOCAL"
strip_realm = true

[[user]]
name = "server2"
principal = "server2@PGDOG.LOCAL"
strip_realm = true

[[user]]
name = "principal1"
principal = "principal1@PGDOG.LOCAL"
strip_realm = false

[[user]]
name = "principal2"
principal = "principal2@PGDOG.LOCAL"
strip_realm = false
