[general]
resharding_copy_format = "binary"

#
# Source of data.
#
[[databases]]
name = "source"
host = "127.0.0.1"
database_name = "pgdog"

#
# Reshard 0 -> 2
#
[[databases]]
name = "destination"
host = "127.0.0.1"
database_name = "pgdog1"
shard = 0

[[databases]]
name = "destination"
host = "127.0.0.1"
database_name = "pgdog2"
shard = 1

[[sharded_tables]]
database = "destination"
column = "tenant_id"
data_type = "bigint"

#
# Reshard 2 -> 2
#
[[databases]]
name = "destination2"
host = "127.0.0.1"
database_name = "shard_0"
shard = 0

[[databases]]
name = "destination2"
host = "127.0.0.1"
database_name = "shard_1"
shard = 1

[[sharded_tables]]
database = "destination2"
column = "tenant_id"
data_type = "bigint"

[admin]
password = "pgdog"
