[general]
dry_run = true

[rewrite]
enabled = false
shard_key = "ignore"
split_inserts = "error"

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[admin]
password = "pgdog"

[[sharded_tables]]
database = "pgdog"
name = "Users"
column = "id"
data_type = "bigint"
