# Connection targets used by the SQL regression suite.
targets:
  postgres_standard_text:
    dsn: postgresql://pgdog:pgdog@127.0.0.1:5432/pgdog
    format: text
    tags: [standard]
  postgres_standard_binary:
    dsn: postgresql://pgdog:pgdog@127.0.0.1:5432/pgdog
    format: binary
    tags: [standard]
  pgdog_standard_text:
    dsn: postgresql://pgdog:pgdog@127.0.0.1:6432/pgdog
    format: text
    tags: [standard]
  pgdog_standard_binary:
    dsn: postgresql://pgdog:pgdog@127.0.0.1:6432/pgdog
    format: binary
    tags: [standard]
  pgdog_sharded_text:
    dsn: postgresql://pgdog:pgdog@127.0.0.1:6432/pgdog_sharded
    format: text
    tags: [sharded]
  pgdog_sharded_binary:
    dsn: postgresql://pgdog:pgdog@127.0.0.1:6432/pgdog_sharded
    format: binary
    tags: [sharded]

pairs:
  - name: standard_text
    baseline: postgres_standard_text
    candidate: pgdog_standard_text
    tags: [standard]
  - name: standard_binary
    baseline: postgres_standard_binary
    candidate: pgdog_standard_binary
    tags: [standard]
  - name: sharded_text
    baseline: postgres_standard_text
    candidate: pgdog_sharded_text
    tags: [sharded]
  - name: sharded_binary
    baseline: postgres_standard_binary
    candidate: pgdog_sharded_binary
    tags: [sharded]
