[[databases]]
name = "pgdog"
host = "127.0.0.1"

[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_0"
shard = 0

[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_1"
shard = 1

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5433
role = "primary"

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5434
role = "replica"

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5435
role = "replica"

[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded"
column = "id"
data_type = "bigint"
primary = true

[admin]
password = "pgdog"
