# ------------------------------------------------------------------------------
# ----- General ----------------------------------------------------------------

[general]
query_timeout = 1_000
checkout_timeout = 1_000
connect_timeout = 1_000
load_balancing_strategy = "round_robin"
rollback_timeout = 1_000
read_write_strategy = "aggressive"
openmetrics_port = 9090
openmetrics_namespace = "pgdog_"
prepared_statements_limit = 500
# dns_ttl = 15_000
query_cache_limit = 500
pub_sub_channel_size = 4098

# ------------------------------------------------------------------------------
# ----- Database :: pgdog ------------------------------------------------------

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[[databases]]
name = "pgdog"
host = "127.0.0.1"
role = "replica"
read_only = true

# ------------------------------------------------------------------------------
# ----- Database :: pgdog_sharded ----------------------------------------------

[[databases]]
name = "pgdog_sharded"
host = "localhost"
database_name = "shard_0"
shard = 0

[[databases]]
name = "pgdog_sharded"
host = "localhost"
database_name = "shard_1"
shard = 1

[[databases]]
name = "pgdog_sharded"
host = "localhost"
database_name = "shard_0"
shard = 0
role = "replica"

[[databases]]
name = "pgdog_sharded"
host = "localhost"
database_name = "shard_1"
shard = 1
role = "replica"

# ------------------------------------------------------------------------------
# ----- Database :: failover ---------------------------------------------------

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5435
role = "primary"
database_name = "pgdog"

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5436
role = "replica"
database_name = "pgdog"
read_only = true

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5437
role = "replica"
database_name = "pgdog"
read_only = true

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5438
role = "replica"
database_name = "pgdog"
read_only = true

# ------------------------------------------------------------------------------
# ----- Hash Sharded :: BIGINT -------------------------------------------------

[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded"
column = "id"
data_type = "bigint"
primary = true

[[sharded_tables]]
database = "pgdog_sharded"
column = "customer_id"
data_type = "bigint"

# ------------------------------------------------------------------------------
# ----- Hash Sharded :: VARCHAR ------------------------------------------------

[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded_varchar"
column = "id_varchar"
data_type = "varchar"

# ------------------------------------------------------------------------------
# ----- Hash Sharded :: Timestamp Test -----------------------------------------

[[sharded_tables]]
database = "pgdog_sharded"
name = "timestamp_test"
column = "id"
data_type = "bigint"
primary = true

# ------------------------------------------------------------------------------
# ----- Hash Sharded :: UUID ---------------------------------------------------

[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded_uuid"
column = "id_uuid"
data_type = "uuid"

# ------------------------------------------------------------------------------
# ----- Range Sharded :: BIGINT ------------------------------------------------

[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded_range"
column = "id"
data_type = "bigint"

[[sharded_mappings]]
database = "pgdog_sharded"
table = "sharded_range"
column = "id"
kind = "range"
start = 0
end = 100
shard = 0

[[sharded_mappings]]
database = "pgdog_sharded"
table = "sharded_range"
column = "id"
kind = "range"
start = 100
end = 200
shard = 1

# ------------------------------------------------------------------------------
# ----- List Sharded :: BIGINT -------------------------------------------------

[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded_list"
column = "id"
data_type = "bigint"

[[sharded_mappings]]
database = "pgdog_sharded"
table = "sharded_list"
column = "id"
kind = "list"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
shard = 0

[[sharded_mappings]]
database = "pgdog_sharded"
table = "sharded_list"
column = "id"
kind = "list"
values = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
shard = 1

# ------------------------------------------------------------------------------
# ----- List Sharded :: UUID ---------------------------------------------------

[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded_list_uuid"
column = "id_uuid"
data_type = "uuid"

[[sharded_mappings]]
database = "pgdog_sharded"
table = "sharded_list_uuid"
column = "id_uuid"
kind = "list"
values = ['00000000-0000-0000-0000-000000000000']
shard = 0

[[sharded_mappings]]
database = "pgdog_sharded"
table = "sharded_list_uuid"
column = "id_uuid"
kind = "list"
values = ['11111111-1111-1111-1111-111111111111']
shard = 1

# ------------------------------------------------------------------------------
# ----- Omnisharded Tables -----------------------------------------------------

[[omnisharded_tables]]
database = "pgdog_sharded"
tables = ["sharded_omni"]

# ------------------------------------------------------------------------------
# ----- Admin ------------------------------------------------------------------

[admin]
password = "pgdog"

# ------------------------------------------------------------------------------
# ----- ActiveRecord Tables ----------------------------------------------------
#
#  ActiveRecord sends these queries at startup to figure out the schema.
#  This will route them to only one shard instead of issuing cross-shard
#  queries and getting incorrect results.
#

[[manual_queries]]
fingerprint = "e78fe2c08de5f079" #[16685804461073231993]

[[manual_queries]]
fingerprint = "43258d068030bb3e" #[4838428433739463486]

[[manual_queries]]
fingerprint = "08aab2cee482a97d" #[624508100011010429]

[[manual_queries]]
fingerprint = "23cd60d5972d1712" #[2579824632033777426]

[[manual_queries]]
fingerprint = "bb38525ebeb46656" #[13490623250668217942]

[[manual_queries]]
fingerprint = "f4814b6fadabc4c1" #[17618446160277259457]

[[manual_queries]]
fingerprint = "04dc05f480b702d3"

[[manual_queries]]
fingerprint = "2d9944fc9caeaadd" # [3285733254894627549]

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
