name: benchmarks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  bench:
    runs-on: blacksmith-32vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v6
      - name: Install CI deps
        run: bash integration/ci/install-deps.sh
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: build-v1
      - name: Build base
        run: |
          git fetch --depth=1 origin ${{ github.event.pull_request.base.sha || 'main' }}
          git checkout FETCH_HEAD
          cargo build --release --bin pgdog
          cp target/release/pgdog ${{ runner.temp }}/pgdog-base
          git checkout ${{ github.sha }}
      - name: Build head
        run: |
          cargo build --release --bin pgdog
          cp target/release/pgdog ${{ runner.temp }}/pgdog-head
      - name: Setup PostgreSQL
        run: bash integration/ci/setup.sh
      - name: Run benchmarks
        shell: bash
        run: |
          for name in pooler lb sharding; do
            for rev in base head; do
              PGDOG_BIN=${{ runner.temp }}/pgdog-$rev bash benches/perf/run.sh $name | tee ${{ runner.temp }}/$name-$rev.txt
            done
          done
      - name: TPS
        run: grep '^tps' ${{ runner.temp }}/{pooler,lb,sharding}-{base,head}.txt
