name: fmt
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fmt:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    container:
      image: ghcr.io/pgdogdev/pgdog-ci-base:latest
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        working-directory: pgdog
        run: cargo clippy
