name: fmt
on:
  push:
    branches:
      - main
      - main-ent
    paths:
      - ".github/workflows/fmt.yml"
      - "**/*.rs"
      - "integration/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/fmt.yml"
      - "**/*.rs"
      - "integration/**"

jobs:
  fmt:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci-deps
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
