name: macos
on:
  push:
    branches:
      - main
      - main-ent
    paths:
      - "**/*.rs"
      - "integration/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.rs"
      - "integration/**"

jobs:
  macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
