name: plugin-ci
on:
  push:
    branches:
      - main
      - main-ent
    paths:
      - "**/*.rs"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.rs"

jobs:
  plugin-unit-tests:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - name: Install CI deps
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 5
          run: bash integration/ci/install-deps.sh
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "plugin-unit-v1"
      - name: Run plugin unit tests
        run: cargo nextest run -E 'package(pgdog-example-plugin)' --no-fail-fast
